INSERT INTO company(id, country_code, country_name, image_url, name, sector, site_url, description) VALUES
     (nextval('company_serial'), 'usa', 'США', 'apple', 'Apple', 'Технологии', 'https://www.apple.com/ru/',
      'Apple — американская корпорация, производитель персональных и планшетных компьютеров, аудиоплееров, смартфонов, программного обеспечения и цифрового контента.'),
     (nextval('company_serial'), 'swe', 'Швеция', 'abb', 'Abb', 'Технологии', 'https://new.abb.com/ru','ABB — шведско-швейцарская транснациональная корпорация, специализирующаяся в области электротехники и энергетического машиностроения.'),
     (nextval('company_serial'), 'usa', 'США', 'hp', 'HP', 'Технологии', 'https://hp-rus.com/','Hewlett-Packard — созданная в 1939 году компания-поставщик аппаратного и программного обеспечения для организаций и индивидуальных потребителей.'),
     (nextval('company_serial'), 'usa', 'США', 'ibm', 'IBM', 'Технологии', 'https://www.ibm.com/about/russia/','IBM — американская компания со штаб-квартирой в (штат Нью-Йорк), один из крупнейших в мире производителей и поставщиков аппаратного и программного обеспечения'),
     (nextval('company_serial'), 'fin', 'Финляндия', 'nokia', 'Nokia', 'Технологии', 'https://www.nokia.com/phones/ru_ru','Nokia Corporation (фин. Nokia Oyj, произносится но́киа) — финская транснациональная компания, производитель телекоммуникационного оборудования для мобильных, фиксированных, широкополосных и IP-сетей. В 2000-е годы доминировала на мировом рынке мобильных телефонов (с 2013 года телефоны под маркой Nokia выпускаются другими производителями).'),
     (nextval('company_serial'), 'usa', 'США', 'mcdonalds', 'McDonald''s', 'Общепит', 'https://www.mcdonalds.com/us/en-us.html','McDonald’s — американская корпорация, работающая в сфере общественного питания, крупнейшая в мире сеть ресторанов быстрого питания, работающая по системе франчайзинга.'),
     (nextval('company_serial'), 'swe', 'Швеция', 'ikea', 'IKEA', 'Потребление', 'https://www.ikea.com/ru/ru/','IKEA (ИКЕА) — основанная в Швеции нидерландская производственно-рознично торговая группа, одна из крупнейших в мире торговых сетей по продаже мебели и товаров для дома. Юридическое название — Ingka.'),
     (nextval('company_serial'), 'usa', 'США', 'coca-cola', 'Coca-Cola', 'Потребление', 'https://www.coca-cola.ru/','The Coca-Cola Company is an American multinational beverage corporation, best known as the producer of Coca-Cola. The sugary drink was invented in 1886 by pharmacist John Stith Pemberton.'),
     (nextval('company_serial'), 'de', 'Германия', 'dhl', 'DHL', 'Логистика', 'https://www.dhl.com/global-en/home.html','DHL — международная компания экспресс-доставки грузов и документов, лидер мирового и российского логистических рынков.'),
     (nextval('company_serial'), 'usa', 'США', 'nike', 'Nike', 'Одежда', 'https://www.nike.com/ru/','Nike, Inc. — американская транснациональная компания, специализирующаяся на спортивной одежде и обуви. Штаб-квартира — в городе Бивертон (штат Орегон).'),
     (nextval('company_serial'), 'usa', 'США', 'spotify', 'Spotify', 'Сервисы', 'https://open.spotify.com/','Spotify — стриминговый сервис, позволяющий легально прослушивать музыкальные композиции, аудиокниги и подкасты, не скачивая их на устройство.'),
     (nextval('company_serial'), 'usa', 'США', 'airbnb', 'Airbnb', 'Сервисы', 'https://airbnb.ru/','Airbnb (рус. «Эйрбиэнби») — онлайн-площадка для размещения и поиска краткосрочной аренды частного жилья по всему миру. Пользователи Airbnb имеют возможность сдавать путешественникам в аренду своё жильё целиком или частично.'),
     (nextval('company_serial'), 'usa', 'США', 'starbucks', 'Starbucks', 'Общепит', 'https://www.starbucks.com/','Starbucks Corporation, «Ста́рбакс» — американская компания по продаже кофе и одноимённая сеть кофеен.'),
    (nextval('company_serial'), 'jp', 'Япония', 'uniqlo', 'Uniqlo', 'Одежда', 'https://www.uniqlo.com/ru/estore/','Uniqlo — японская розничная сеть повседневной одежды. Компания является дочерней компанией Fast Retailing.'),
    (nextval('company_serial'), 'jp', 'Швеция', 'hm', 'H&M', 'Одежда', 'https://www2.hm.com/ru_ru/index.html','H&M — шведская компания, крупнейшая в Европе розничная сеть по торговле одеждой, штаб-квартиры которой находятся в Стокгольме и Нью-Йорке.'),
    (nextval('company_serial'), 'de', 'Германия', 'volkswagen', 'Volkswagen', 'Авто', 'https://www.volkswagen.ru/ru.html','Volkswagen — немецкая автомобильная марка, одна из многих, принадлежащих концерну Volkswagen AG. Под этой маркой в 2019 году было реализовано 6 млн 620 тыс. автомобилей.'),
    (nextval('company_serial'), 'usa', 'США', 'converse', 'Converse', 'Одежда', 'https://www.converse.com/country-language-selector','Converse — американская компания, производящая обувь с начала XX века и наиболее известная своими кедами Chuck Taylor All-Star. Контролируется компанией Nike.'),
    (nextval('company_serial'), 'usa', 'США', 'converse', 'Converse', 'Одежда', 'https://www.converse.com/country-language-selector','Converse — американская компания, производящая обувь с начала XX века и наиболее известная своими кедами Chuck Taylor All-Star. Контролируется компанией Nike.'),
    (nextval('company_serial'), 'fr', 'Франция', 'michelin', 'Michelin', 'Авто', 'https://www.michelin.ru/','Michelin (произносится Мишлен) (Euronext: ML) — французская компания, производитель шин, один из лидеров в своей отрасли.'),
    (nextval('company_serial'), 'au', 'Австралия', 'canva', 'Canva', 'Сервисы', 'https://www.michelin.ru/','Canva — это бесплатный онлайн-инструмент для графического дизайна. Здесь вы можете создавать публикации для социальных сетей, презентации, плакаты, видео, логотипы и многое другое.'),
    (nextval('company_serial'), 'de', 'Германия', 'wella', 'Wella', 'Потребление', 'https://www.wella.com/selector','Wella AG — немецкая компания, является одной из ведущих компаний в мире в области косметики и парфюмерии.'),
    (nextval('company_serial'), 'il', 'Израиль', 'gett', 'Gett', 'Сервисы', 'https://gett.com/ru/','Gett (пред. название GetTaxi) — израильская компания, предоставляющая сервис такси в Израиле, России, Великобритании и США.'),
    (nextval('company_serial'), 'usa', 'США', 'svetocopy', 'SvetoCopy', 'Потребление', 'https://svetocopy.com/','Один из крупнейших международных производителей бумаги, целлюлозы и упаковки из возобновляемого древесного волокна. Штаб-квартира - в городе Мемфис, штат Теннесси.'),
    (nextval('company_serial'), 'de', 'Германия', 'siemens', 'Siemens', 'Технологии', 'https://svetocopy.com/','Немецкий конгломерат, работающий в области электротехники, электроники, энергетического оборудования, транспорта, медицинского оборудования и светотехники, а также специализированных услуг в различных областях промышленности, транспорта и связи. Штаб-квартиры находятся в Берлине и Мюнхене.'),
    (nextval('company_serial'), 'fr', 'Франция', 'сoty', 'Coty', 'Потребление', 'https://www.coty.com/','«Coty» — французско-американский производитель косметических продуктов. Компания была основана в 1904 году в Париже парфюмером Франсуа Коти.'),
    (nextval('company_serial'), 'usa', 'США', 'johnsonjohnson', 'Johnson & Johnson', 'Потребление', 'https://jnj.ru/','Johnson & Johnson, «Джонсон энд Джонсон»[3] (NYSE: JNJ) — американская холдинговая компания, возглавляющая группу из более чем 250 дочерних компаний по всему миру, производящих лекарственные препараты, санитарно-гигиенические товары и медицинское оборудование.'),
    (nextval('company_serial'), 'nl', 'Нидерланды', 'heineken', 'Heineken', 'Потребление', 'https://www.heinekenrussia.ru/','Heineken (МФА: [ˈɦɛi̯nəkə(n)]), «Хейнекен») — нидерландская пивоваренная компания, крупнейшая в стране и вторая по величине в мире (после Anheuser-Busch InBev).'),
    (nextval('company_serial'), 'usa', 'США', 'westernunion', 'Western Union', 'Финансы', 'https://www.westernunion.ru/ru/ru/home.html','The Western Union Company — американская компания, специализирующаяся на предоставлении услуг денежного посредничества. Основана в 1851 году.'),
    (nextval('company_serial'), 'usa', 'США', 'vans', 'Vans', 'Одежда', 'https://vans.ru/','Vans — производитель обуви и предметов одежды для занятий спортом с середины 60-х годов XX века. Первая пара обуви была продана этой компанией в 1966 году.'),
    (nextval('company_serial'), 'de', 'Германия', 'deutschebank', 'Deutsche Bank', 'Финансы', 'https://www.db.com/','Deutsche Bank (также Дойче банк, Немецкий банк) — крупнейший по числу сотрудников и сумме активов финансовый конгломерат Германии. Правление банка располагается во Франкфурте-на-Майне.'),
    (nextval('company_serial'), 'usa', 'США', 'paypal', 'PayPal', 'Сервисы', 'https://www.paypal.com/ru/home','Крупнейшая дебетовая электронная платёжная система. Позволяет клиентам оплачивать счета и покупки, отправлять и принимать денежные переводы. '),
    (nextval('company_serial'), 'de', 'Германия', 'bmw', 'BMW', 'Авто', 'https://www.bmw.ru/ru/index.html','Немецкий производитель автомобилей, мотоциклов, двигателей, а также велосипедов.'),
    (nextval('company_serial'), 'de', 'Германия', 'audi', 'Audi', 'Авто', 'https://www.bmw.ru/ru/index.html','Немецкая автомобилестроительная компания в составе концерна Volkswagen Group, специализирующаяся на выпуске автомобилей под маркой Audi.'),
    (nextval('company_serial'), 'usa', 'США', 'paramount', 'Paramount Pictures', 'Развлечения и игры', 'https://www.paramount.com/','Paramount Pictures Corporation — американская компания, которая занимается созданием и распространением фильмов. Расположена в Голливуде, штат Калифорния.'),
    (nextval('company_serial'), 'usa', 'США', 'universalpictures', 'Universal Pictures', 'Развлечения и игры', 'https://www.universalpictures.com/','Universal Pictures — старейшая из ныне существующих голливудских киностудий. Основана Карлом Леммле в 1912 году. С 1915 по 1925 год — крупнейшая из кинокомпаний США.'),
    (nextval('company_serial'), 'usa', 'США', 'sony_pictures_entertainment', 'Sony Pictures Entertainment', 'Развлечения и игры', 'https://www.sonypictures.com/','Sony Pictures Entertainment, Inc. — американская кинокомпания, производитель и дистрибьютор фильмов и телевизионных программ.'),
    (nextval('company_serial'), 'pl', 'Польша', 'cd_projekt', 'CD Projekt RED', 'Развлечения и игры', 'https://www.cdprojekt.com/en/','Польская холдинговая компания, издатель, локализатор и разработчик компьютерных игр. Значительный успех, позволивший компании продолжить развитие, имели локализации Diablo и Baldurs Gate.'),
    (nextval('company_serial'), 'usa', 'США', 'electronic_arts', 'Electronic Arts', 'Развлечения и игры', 'https://www.ea.com/ru-ru','Американская корпорация, занимающаяся распространением и изданием компьютерных игр со штаб-квартирой в Редвуд-Сити, штат Калифорния.'),
    (nextval('company_serial'), 'usa', 'США', 'microsoft', 'Microsoft', 'Технологии', 'https://www.microsoft.com/ru-ru','Одна из крупнейших транснациональных компаний по производству проприетарного программного обеспечения для различного рода вычислительной техники - персональных компьютеров, игровых приставок, КПК, мобильных телефонов и прочего.'),
    (nextval('company_serial'), 'usa', 'США', 'amd', 'AMD', 'Технологии', 'https://www.amd.com/ru/','Американский производитель интегральной микросхемной электроники, один из крупнейших производителей центральных процессоров, графических процессоров и адаптеров, материнских плат и чипсетов для них, а также твердотельных накопителей под торговой маркой Radeon.'),
    (nextval('company_serial'), 'usa', 'США', 'nvidia', 'Nvidia', 'Технологии', 'https://www.nvidia.com/ru-ru/','Американская технологическая компания, разработчик графических процессоров и систем на чипе.'),
    (nextval('company_serial'), 'usa', 'США', 'netflix', 'Netflix', 'Развлечения и игры', 'http://netflix.com/','Американская развлекательная компания, а также стриминговый сервис фильмов и сериалов. Основана 29 августа 1997 года Ридом Хастингсом и Марком Рэндольфом.'),
    (nextval('company_serial'), 'de', 'Германия', 'adidas', 'Adidas', 'Одежда', 'https://www.adidas.ru/','Adidas AG — немецкая транснациональная компания по производству спортивной одежды, обуви и аксессуаров.'),
    (nextval('company_serial'), 'usa', 'США', 'victorias_secret', 'Victorias''s Secret', 'Одежда', 'https://www.victoriassecret.com/ru/','Одна из наиболее известных в мире компаний по продаже женского нижнего белья, купальников, одежды, косметики, парфюмерии и аксессуаров. Базируется в Колумбусе, штат Огайо, США.'),
    (nextval('company_serial'), 'fin', 'Финляндия', 'rovio_entertainment', 'Rovio Entertainment', 'Развлечения и игры', 'https://www.rovio.com/','Финский разработчик, издатель и дистрибьютор видеоигр со штаб-квартирой в Эспоо, Финляндия.'),
    (nextval('company_serial'), 'usa', 'США', 'master_card', 'MasterCard', 'Сервисы', 'https://www.mastercard.ru/ru-ru.html','Mastercard Inc. — международная платёжная система, транснациональная финансовая корпорация, объединяющая 22 тысячи финансовых учреждений в 210 странах мира.'),
    (nextval('company_serial'), 'usa', 'США', 'visa', 'Visa', 'Сервисы', 'https://www.mastercard.ru/ru-ru.html','Американская транснациональная компания, предоставляющая услуги проведения платёжных операций. Является основой одноимённой ассоциации. С 20 сентября 2013 года цена её акций участвует в расчёте индекса Доу Джонса.'),
    (nextval('company_serial'), 'usa', 'США', 'disney', 'Disney', 'Развлечения и игры', 'https://disney.ru/','Один из крупнейших медиаконгломератов индустрии развлечений в мире. Первоначально компания Disney была основана 16 октября 1923 года братьями Уолтом и Роем Диснеем как Disney Brothers Studio.'),



INSERT INTO list(id, date_back, date_left, news_url, company_id, status, comment)
values
    (nextval('list_serial'), null, '20220302', 'https://www.kommersant.ru/doc/5238848', 1, 'Покинула',
     'Apple прекращает работу в России, пишет Reuters со ссылкой на заявление компании. «Мы глубоко обеспокоены вторжением России в Украину и поддерживаем всех людей, которые страдают в результате насилия»,— говорится в заявлении Apple.'),
    (nextval('list_serial'), null, '20220721', 'https://lenta.ru/news/2022/07/21/abb/#:~:text=%D0%A8%D0%B2%D0%B5%D0%B4%D1%81%D0%BA%D0%BE%2D%D1%88%D0%B2%D0%B5%D0%B9%D1%86%D0%B0%D1%80%D1%81%D0%BA%D0%B0%D1%8F%20%D0%BA%D0%BE%D0%BC%D0%BF%D0%B0%D0%BD%D0%B8%D1%8F%20ABB%2C%20%D0%BF%D1%80%D0%BE%D0%B8%D0%B7%D0%B2%D0%BE%D0%B4%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%20%D1%8D%D0%BB%D0%B5%D0%BA%D1%82%D1%80%D0%BE%2D,%D1%81%D1%80%D0%B0%D0%B7%D1%83%20%D0%BF%D0%BE%D1%81%D0%BB%D0%B5%20%D0%BD%D0%B0%D1%87%D0%B0%D0%BB%D0%B0%20%D0%B2%D0%BE%D0%B5%D0%BD%D0%BD%D0%BE%D0%B9%20%D0%BE%D0%BF%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D0%B8', 2, 'Покинула',
     'ABB has decided to exit the Russian market due to the ongoing war in Ukraine and impact of related international sanctions. The financial impact in the second quarter amounted to -$57 million of which -$23 million will impact cash flow in the third quarter.
 When the war broke out, ABB stopped taking new orders in Russia. At the same time, it has been fulfilling a small number of existing contractual obligations with local customers, in compliance with applicable sanctions.
 Most of ABB’s dedicated Russian workforce has been on leave since March of this year and the company will do its best to support them as it realigns its operations in a controlled manner.'),
    (nextval('list_serial'), null, '20220601', 'https://quote.rbc.ru/news/short_article/6298a36a9a7947aae1a209be#:~:text=%D0%9F%D1%80%D0%BE%D0%B8%D0%B7%D0%B2%D0%BE%D0%B4%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%20%D0%BD%D0%BE%D1%83%D1%82%D0%B1%D1%83%D0%BA%D0%BE%D0%B2%20HP%20%D0%BE%D0%B1%D1%8A%D1%8F%D0%B2%D0%B8%D0%BB%20%D0%BE%D0%B1,%D0%BE%D1%81%D1%82%D0%B0%D0%B2%D1%88%D0%B5%D0%B3%D0%BE%D1%81%D1%8F%20%D0%B1%D0%B8%D0%B7%D0%BD%D0%B5%D1%81%D0%B0%20%D0%B8%D0%B7%20%D1%8D%D1%82%D0%B8%D1%85%20%D1%81%D1%82%D1%80%D0%B0%D0%BD', 3, 'Покинула',
     'Для нас больше не представляется целесообразным продолжать деятельность в России и Белоруссии, мы приступаем к упорядоченному выводу оставшегося бизнеса из этих стран. Мы ожидаем дополнительных списаний в третьем квартале 2022 года в связи с нашим решением, но эти потери не будут существенными.'),
    (nextval('list_serial'), null, '20220305', 'https://www.cnews.ru/news/top/2022-03-06_rossiya_ostalas_bez_ibmpod', 4, 'Покинула',
     'Помимо того, что мы не продаем технологии в России, мы не ведем дела с российскими военными организациями» (In addition to not selling technology in Russia, we do not do business with Russian military organizations).'),
    (nextval('list_serial'), null, '20220301', 'https://www.ixbt.com/news/2022/04/12/nokia-uhodit-s-rossijskogo-rynka.html', 5, 'Покинула',
     'Дальнейшее присутствие Nokia в России невозможно. За последние недели мы приостановили поставки, прекратили новый бизнес и переносим нашу ограниченную научно-исследовательскую деятельность за пределы России. Теперь мы можем объявить о выходе с российского рынка. В ходе этого процесса нашим приоритетом остаётся безопасность и благополучие наших сотрудников.'),
    (nextval('list_serial'), null, '20220516', 'https://www.ixbt.com/news/2022/03/09/mcdonald-s-62.html#:~:text=McDonald''s%20%D0%B7%D0%B0%D0%BA%D1%80%D1%8B%D0%B2%D0%B0%D0%B5%D1%82%20%D0%B2%D1%81%D0%B5%20%D1%80%D0%B5%D1%81%D1%82%D0%BE%D1%80%D0%B0%D0%BD%D1%8B%20%D0%B2,%D0%BF%D1%80%D0%B8%D0%BE%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%B8%D1%82%D1%8C%20%D0%B2%D1%81%D0%B5%20%D0%BE%D0%BF%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D0%B8%20%D0%BD%D0%B0%20%D1%80%D1%8B%D0%BD%D0%BA%D0%B5', 6, 'Покинула',
     'McDonald''s принял решение временно закрыть все свои рестораны в России и приостановить все операции на рынке. В России у нас работает 62 000 человек, которые вложили свое сердце и душу в наш бренд McDonald''s, чтобы служить своим сообществам.'),
    (nextval('list_serial'), null, '20220303', 'https://www.kommersant.ru/doc/5514279', 7, 'Покинула',
     'За последние несколько месяцев ситуация с бизнес-процессами и цепочками поставок по всему миру сильно ухудшилась. Ввиду этого мы не видим возможности возобновить продажи в обозримом будущем. Как следствие, группа компаний Inter IKEA и группа компаний Ingka приняли решение сократить масштаб бизнеса в России. Это трудное решение, но мы верим в то, что оно необходимо», — сообщили представители компании.'),
    (nextval('list_serial'), null, '20220622', 'https://www.forbes.ru/biznes/469591-coca-cola-uhodit-iz-rossii-cto-proishodit-na-samom-dele', 8, 'Покинула',
     'Дистрибьютор Coca-Cola в России — Coca-Cola HBC — сообщил, что больше не будет производить и продавать напитки бренда в стране.'),
    (nextval('list_serial'), null, '20220729', 'https://www.retail.ru/news/dhl-ukhodit-iz-rossii-30-iyulya-2022-219038/', 9, 'Покинула',
     'DHL объяснила свое решение об уходе из России «существенными техническими сложностями в функционировании информационных систем и глобальной операционной структуры, а также законодательными ограничениями».'),
    (nextval('list_serial'), null, '20220523', 'https://www.rbc.ru/business/25/05/2022/628d58f99a79478331268087', 10, 'Покинула',
     'Американская компания Nike, специализирующаяся на выпуске спортивной обуви и одежды, не продлила соглашение со своим франчайзи Inventive Retail Group (IRG) из-за отсутствия возможности «в обозримом будущем» доставить продукцию в Россию'),
    (nextval('list_serial'), null, '20220325', 'https://www.kommersant.ru/doc/5280554#:~:text=Spotify%20%D1%83%D0%B9%D0%B4%D0%B5%D1%82%20%D0%B8%D0%B7%20%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D0%B8.%20%D0%A1%D1%82%D1%80%D0%B8%D0%BC%D0%B8%D0%BD%D0%B3%D0%BE%D0%B2%D1%8B%D0%B9,%D0%BD%D0%BE%D0%B2%D0%BE%D1%81%D1%82%D0%B8%20%D0%B8%20%D0%B8%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D1%8E%20%D0%B2%20%D1%80%D0%B5%D0%B3%D0%B8%D0%BE%D0%BD%D0%B5', 11, 'Покинула',
     'Spotify по-прежнему считает, что крайне важно поддерживать работу нашего сервиса в России, чтобы предоставлять надежные, независимые новости и информацию в регионе. К сожалению, недавно принятый закон еще больше ограничивает доступ к информации, устраняет свободу слова и новостей, ставит под угрозу безопасность сотрудников Spotify и, возможно, даже наших слушателей. После тщательного рассмотрения наших вариантов и текущих обстоятельств мы пришли к сложному решению полностью приостановить наш сервис в России'),
    (nextval('list_serial'), null, '20220404', 'https://ria.ru/20220306/oteli-1776803374.html', 12, 'Покинула',
     'Airbnb приостанавливает всю деятельность в России и Белоруссии'),
    (nextval('list_serial'), null, '20220523', 'https://www.rbc.ru/business/23/05/2022/628b99109a7947e75d98e338', 13, 'Покинула',
     'As we mentioned on March 8, we have suspended all business activity in Russia, including shipment of all Starbucks products. Starbucks has made the decision to exit and no longer have a brand presence in the market. We will continue to support the nearly 2,000 green apron partners in Russia, including pay for six months and assistance for partners to transition to new opportunities outside of Starbucks.'),
    (nextval('list_serial'), null, '20220308', 'https://www.forbes.ru/forbeslife/458525-aponskaa-set-magazinov-odezdy-uniqlo-vremenno-priostanavlivaet-deatel-nost-v-rossii', 14, 'Покинула',
     'Группой компаний Fast Retailing было принято решение о временной приостановке работы. Все 50 магазинов UNIQLO в России, а также интернет‑магазин временно приостановили свою работу с 21 марта 2022 г.'),
    (nextval('list_serial'), null, '20220718', 'https://www.rbc.ru/business/18/07/2022/62d507d59a7947e1e2814ae8#:~:text=%D0%A0%D0%B5%D1%82%D0%B5%D0%B9%D0%BB%D0%B5%D1%80%20H%26M%20%D1%80%D0%B5%D1%88%D0%B8%D0%BB%20%D1%83%D0%B9%D1%82%D0%B8%20%D0%B8%D0%B7,%E2%80%94%20%D0%B7%D0%B0%D1%8F%D0%B2%D0%B8%D0%BB%D0%B0%20%D0%B3%D0%B5%D0%BD%D0%B4%D0%B8%D1%80%D0%B5%D0%BA%D1%82%D0%BE%D1%80%20%D0%A5%D0%B5%D0%BB%D0%B5%D0%BD%D0%B0%20%D0%A5%D0%B5%D0%BB%D1%8C%D0%BC%D0%B5%D1%80%D1%81%D1%81%D0%BE%D0%BD', 15, 'Покинула',
     'Компания H&M Group приняла решение остановить бизнес в России. В связи с этим сайт hm.com временно недоступен в этом регионе.'),
    (nextval('list_serial'), null, '20220705', 'https://www.gazeta.ru/auto/2022/07/27/15188336.shtml', 16, 'Покинула',
     'В связи с высоким общим уровнем неопределенности мы не можем предсказать дату возврата к обычному режиму производства в России и планировать производство на 2022 год'),
    (nextval('list_serial'), null, '20220630', 'https://lenta.ru/news/2022/06/30/converse/', 17, 'Покинула',
     'По словам работников, официальный русскоязычный сайт указанного бренда перестанет функционировать на следующей неделе — 4 или 5 июля. Однако на данный момент на нем отсутствует соответствующее предупреждение.'),
   (nextval('list_serial'), null, '20220628', 'https://lenta.ru/news/2022/06/28/mich/#:~:text=Michelin%20%D1%83%D0%B9%D0%B4%D0%B5%D1%82%20%D0%B8%D0%B7%20%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D0%B8.%20Michelin,%D0%BB%D0%BE%D0%B3%D0%B8%D1%81%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D1%85%20%D1%81%D0%B1%D0%BE%D0%B5%D0%B2%20%D0%B8%20%C2%AB%D0%BE%D0%B1%D1%89%D0%B5%D0%B9%20%D0%BD%D0%B5%D0%BE%D0%BF%D1%80%D0%B5%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%BD%D0%BE%D1%81%D1%82%D0%B8%C2%BB', 18, 'Покинула',
     'Компания утверждает, что не может возобновить производство по техническим причинам — из-за логистических сбоев и «общей неопределенности». Ожидается, что передача контроля над активами произойдет до конца 2022 года. При этом Michelin обещает создать максимально благоприятные условия для сотрудников.'),
 (nextval('list_serial'), null, '20220601', 'https://www.dp.ru/a/2022/06/01/Servis_dlja_dizajna_Canva', 19, 'Покинула',
     'Canva больше недоступна в России. В официальных сообществах сервиса в соцсети "ВКонтакте" и в Telegram никаких сообщений или комментариев на этот счёт нет. Страницы перестали обновляться в конце февраля 2022 года.'),
 (nextval('list_serial'), null, '20220527', 'https://www.rbc.ru/business/27/05/2022/6291098a9a794754137884e0', 20, 'Покинула',
     'Компания передала право собственности независимой российской операционной команде, состоящей из бывших сотрудников Wella Company, «для завершения выхода с рынка в полном соответствии с местным законодательством». «Передача права собственности вступает в силу немедленно. Компания Wella не получит прибыли от этой сделки», — говорится в письме.'),
 (nextval('list_serial'), null, '20220516', 'https://www.rbc.ru/business/16/05/2022/628265a69a79471d955b1e35#:~:text=%D0%90%D0%B3%D1%80%D0%B5%D0%B3%D0%B0%D1%82%D0%BE%D1%80%20%D1%82%D0%B0%D0%BA%D1%81%D0%B8%20Gett%20%D0%BF%D1%80%D0%B5%D0%BA%D1%80%D0%B0%D1%82%D0%B8%D1%82%20%D0%BF%D0%BE%D0%B4%D0%B4%D0%B5%D1%80%D0%B6%D0%BA%D1%83,%D0%B7%D0%B0%D0%BA%D0%B0%D0%B7%D0%BE%D0%B2%C2%BB%2C%20%E2%80%94%20%D0%B3%D0%BE%D0%B2%D0%BE%D1%80%D0%B8%D1%82%D1%81%D1%8F%20%D0%B2%20%D0%BF%D0%B8%D1%81%D1%8C%D0%BC%D0%B5', 21, 'Покинула',
     'Глобальным офисом Gett было принято решение о прекращении 31 мая 2022 года технической поддержки, доработки и обеспечения функционирования программного обеспечения, которое используется для приемов и обработки заказов'),
 (nextval('list_serial'), null, '20220513', 'https://lenta.ru/news/2022/05/13/svetocopy/', 22, 'Покинула',
     'Мы приняли решение покинуть Россию. Мы будем делать это в установленном порядке и ведем процесс продажи нашего российского бизнеса. Мы работаем над достижением соглашения и планируем завершить этот процесс в кратчайшие сроки, включая получение одобрения нашего совета директоров, а также необходимых разрешений правительства для выполнения сделки'),
 (nextval('list_serial'), null, '20220512', 'https://www.bfm.ru/news/499804', 23, 'Покинула',
     'Siemens уйдет с российского рынка из-за войны на Украине», — поясняется в сообщении'),
 (nextval('list_serial'), null, '20220428', 'https://www.kommersant.ru/doc/5329386', 24, 'Покинула',
     'Coty said it does not expect the move to impact its fiscal 2022 revenue and profit targets, citing the seasonally lower contribution of the Russia business in its fourth quarter.'),
 (nextval('list_serial'), null, '20220329', 'https://spb.tsargrad.tv/news/johnson-johnson-uhodit-iz-rossii-no-chastichno-kakih-tovarov-bolshe-ne-budet-na-polkah-magazinov_520409/nsk', 25, 'Покинула',
     'Мы приняли решение приостановить поставки наших средств личной гигиены в Россию, — говорится в заявлении компании.'),
 (nextval('list_serial'), null, '20220328', 'https://lenta.ru/news/2022/08/01/heineken/', 26, 'Покинула',
     'On 28 March, HEINEKEN announced its decision to leave Russia. We are making good progress to secure an orderly transfer of our business to a new owner in full compliance with international and local laws and expect to reach an agreement during the second half of this year. For more details on the financial implications of this decision, please refer to page 12.'),
 (nextval('list_serial'), null, '20220324', 'https://lenta.ru/news/2022/02/07/westernunion/', 27, 'Покинула',
     'Платежная Система Вестерн Юнион остановила проведение денежных переводов в России с 24 марта 2022 года. Денежные переводы, отправленные из России в другие страны и не выплаченные получателям до 24 марта 2022 года, доступны для получателей в других странах в любое время (за исключением переводов из России в Республику Беларусь, которые могут быть только возвращены отправителю).'),
 (nextval('list_serial'), null, '20220314', 'https://lenta.ru/news/2022/03/13/vans/', 28, 'Покинула',
     'В настоящее время Vans не может гарантировать доставку товаров покупателям в России. В связи с этим приобретение товаров на веб-сайте vans.ru временно приостановлено. Приносим свои извинения за доставленные неудобства.'),
 (nextval('list_serial'), null, '20220312', 'https://www.rbc.ru/business/12/03/2022/622bd2bf9a7947194ec28a1f', 29, 'Покинула',
     'Как и некоторые из наших международных конкурентов, мы находимся в процессе закрытия нашего оставшегося бизнеса в соответствии с законодательными и нормативными требованиями'),
 (nextval('list_serial'), null, '20220312', 'https://www.kommersant.ru/doc/5249212', 30, 'Покинула',
     'В нынешних обстоятельствах мы приостанавливаем работу PayPal в России'),
 (nextval('list_serial'), null, '20220225', 'https://www.vedomosti.ru/auto/articles/2022/03/01/911583-bmw-uhodit-iz-rossii', 31, 'Покинула',
     'В настоящее время мы работаем над решениями, которые в условиях ограниченных поставок запчастей позволят нам в полной мере выполнять гарантийные обязательства перед клиентами. Мы также продолжим сервисное обслуживание автомобилей наших клиентов с соблюдением всех стандартов BMW'),
 (nextval('list_serial'), null, '20220225', 'https://life.ru/p/1481404', 32, 'Покинула',
     'Audi покидает Россию.'),
 (nextval('list_serial'), null, '20220301', 'https://lenta.ru/news/2022/03/16/paramount/', 33, 'Покинула',
     'Как и многие из вас, я внимательно слежу за разрушительным, ничем не спровоцированным вторжением в Украину. Возникший в результате гуманитарный кризис и его последствия для жизни миллионов людей на Украине, в Восточной Европе и в самой России душераздирающе очевидны'),
 (nextval('list_serial'), null, '20220301', 'https://lenta.ru/news/2022/07/02/universalpic/', 34, 'Покинула',
     'Материнская компания решила прекратить деятельность в РФ, так как вести бизнес стало невозможным из-за многочисленных сложностей, с которыми сталкиваются иностранные компании'),
 (nextval('list_serial'), null, '20220301', 'https://lenta.ru/news/2022/03/12/sonypictures/', 35, 'Покинула',
     'Мы поддерживаем многие компании по всему миру, которые в настоящее время приостановили свою деятельность в России, и поддерживаем гуманитарные усилия, которые в настоящее время проводятся на Украине.'),
 (nextval('list_serial'), null, '20220228', 'https://www.vedomosti.ru/media/articles/2022/03/02/911742-megogo-prekraschaet-deyatelnost', 36, 'Покинула',
     'Уважаемые клиенты, к сожалению, медиасервис MEGOGO Россия останавливает свою работу. Со 2 марта у вас отключена автопролонгация подписок.'),
 (nextval('list_serial'), null, '20220303', 'https://dtf.ru/gameindustry/1105519-cd-projekt-ostanovit-prodazhu-svoih-igr-v-rossii-i-belarusi', 37, 'Покинула',
     'CD PROJEKT Group приняла решение остановить продажи наших игр в России и Беларуси. Это коснется цифровых и физических копий. Мы надеемся на понимание всех игроков, которых это затронет. Ранее купленные копии игр, а также патчи и хотфиксы к ним продолжат работать.'),
 (nextval('list_serial'), null, '20220304', 'https://lenta.ru/news/2022/03/04/ea/', 38, 'Покинула',
     'Согласно заявлению компании, было принято решение о приостановке продаж игр и прочей продукции на время продолжения конфликта.'),
 (nextval('list_serial'), null, '20220304', 'https://lenta.ru/news/2022/03/04/mcrsft/', 39, 'Покинула',
     'Мы останавливаем многие направления нашего бизнеса в России в соответствии с решениями правительств о санкциях.'),
 (nextval('list_serial'), null, '20220304', 'https://lenta.ru/news/2022/03/09/intel/', 40, 'Покинула',
     'В связи с санкциями, наложенными на Россию Соединенными Штатами и другими странами, в настоящее время AMD приостанавливает продажи и распространение нашей продукции в России и Белоруссии.'),
 (nextval('list_serial'), null, '20220306', 'https://lenta.ru/news/2022/03/06/nvidia_stop/', 41, 'Покинула',
     'Мы не продаем в Россию.'),
 (nextval('list_serial'), null, '20220307', 'https://lenta.ru/news/2022/03/08/ub/', 42, 'Покинула',
     'Ubisoft Entertainment SA is “suspending its physical and digital sales” in Russia on the Russian market, a spokesperson for the company said, following similar announcements by major video games companies over the past week.'),
 (nextval('list_serial'), null, '20220307', 'https://lenta.ru/news/2022/05/30/otkluchenie/', 43, 'Покинула',
     'Представитель Netflix назвал ограничение работы платформы в стране «реализацией ухода с российского рынка». По его словам, компания ждала, когда закончится действие всех подписок, ранее оформленных российскими пользователями.'),
 (nextval('list_serial'), null, '20220309', 'https://www.rbc.ru/business/08/03/2022/62266b5d9a7947d348fb389f', 44, 'Покинула',
     'Мы приостанавливаем работу розничных магазинов, сайта и приложения до дальнейшего уведомления.'),
 (nextval('list_serial'), null, '20220309', 'https://www.cossa.ru/news/302350/', 45, 'Покинула',
     'Мы замораживаем и будем продолжать замораживать аккаунты организаций Figma в соответствии с санкциями США и ЕС против России. Мы также прекращаем все новые попытки продаж в России.'),
 (nextval('list_serial'), null, '20220309', 'https://lenta.ru/news/2022/03/09/vsbye/', 46, 'Покинула',
     'В компании аргументировали это тем, что не считают целесообразным возобновлять свою работу на территории России, учитывая «продолжающиеся экономические, логистические и деловые сбои в стране».'),
 (nextval('list_serial'), null, '20220310', 'https://news.rambler.ru/games/48272905-avtory-angry-birds-udalili-svoi-igry-v-rossii/', 47, 'Покинула',
     'По словам Rovio, она удалила все свои игры из Google Play и App Store для пользователей из России и Беларуси. Также компания не выпустит обновления для своих проектов в этих двух странах.'),
(nextval('list_serial'), null, '20220310', 'https://www.vedomosti.ru/finance/news/2022/03/06/912465-mastercard-visa', 48, 'Покинула',
     'Карты, выпущенные российскими банками, больше не будут поддерживаться сетью Mastercard. И любая Mastercard, выпущенная за пределами страны, не будет работать в российских магазинах или банкоматах.'),
(nextval('list_serial'), null, '20220310', 'https://ria.ru/20220306/visa-1776864520.html', 49, 'Покинула',
     'Начиная с этого момента Visa будет работать с клиентами и партнерами в России с целью прекратить все транзакции Visa в ближайшие дни. Когда процесс будет окончен, все транзакции, инициированные картами Visa, выпущенными в РФ, больше не будут работать за пределами страны.'),
(nextval('list_serial'), null, '20220310', 'https://www.forbes.ru/forbeslife/458683-kompania-the-walt-disney-priostanavlivaet-vsu-deatel-nost-v-rossii', 50, 'Покинула',
     'Некоторые виды нашей деятельности в стране будут приостановлены немедленно. Временная остановка других, например, вещание линейных каналов и лицензирование некоторого контента и продуктов, потребует времени из-за договорных сложностей.'),


























